name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 250
      - name: Commit & Push
        run: |
          git config user.name ${{ github.repository_owner }}
          git config user.email 75338261+ressiws@users.noreply.github.com
          git add -A .
          if git commit -m "GitHub 3D Profile"; then
            git push
          fi
